### ISSUE TITLE
상점 기능 단순 시나리오

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#126]
## TODO
- [x] 관리자가 상품을 등록
- [x] 관리자가 등록된 상품을 상점에 등록
- [ ] 회원이 상점에서 아이템을 구매
- [ ] 마이페이지에서 구매한 아이템 확인 가능
