### ISSUE TITLE
알림 기능 리팩토링 및 추가기능 구현

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#159]
## TODO
- [x] 알림 기능
  - [x] 프론트 디자인
  - [x] 시스템 알림 이미지 변경
  - [x] 지난 주 내가 받은 신고 수 매주 월요일 알림 생성
  - [x] 지난 주 내가 받은 좋아요 수 매주 월요일 알림 생성
