### ISSUE TITLE
관리자 통계 기능 추가

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#160]
## TODO
- [ ] 신고내역 관리자가 확인 가능
- [ ] 지난 주 코인 사용 or 획득 통계
- [ ] 지난 주 포인트 사용 통계
- [ ] 챌린지 참여 및 인증 내역 통계
