### ISSUE TITLE
프론트 최종 다듬기

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#185]
## TODO
- [x] 인증 페이지 인증샷 사이즈 조절
- [x] 좋아요 실시간 갱신
- [x] 리포트 페이지 돌아가기 버튼 추가
- [x] 화폐 리포트 쉼표 처리
- [x] 일상지원금 월요일 3천원 지급 적용 여부 확인
