### ISSUE TITLE
챌린지에 대한 리워드 생성과 오픈, 참가시 PrivateReward 설정

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#39]
## 현재 상황
1. 챌린지가 생성되면, BEFORE_SETTINGS라는 상태로 챌린지가 생성된다.

## TODO
- [x] 관리자 페이지에서, 챌린지에 대한 보상 설정을 마친 뒤, 해당 챌린지의 상태를 OPEN으로 변경
- [x] 전체 챌린지 리스트에서는 상태가 OPEN 상태인 챌린지만 확인할 수 있음.
- [x] 챌린지 디테일 페이지에서 참가하기 버튼을 누르면, ChallengeMember 객체가 생성되며, 설정된
	보상(PublicReward)을 기반으로 PrivateReward 객체도 생성된다.
- [x] 참가가 완료된 유저의 디테일 화면에는 인증하기 버튼과 나의 보상 종류가 출력되어야 한다.
- [x] PublicReward가 변경되더라도 화면에 출력되는 보상 내용이 변경되어서는 안된다.
