### ISSUE TITLE
챌린지 서비스 리팩토링 및 유효성 검사

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#41]
## TODO

- [x] 챌린지 서비스의 전반적인 점검 및 리팩토링
	- [x] 챌린지 생성 관련 유효성 검사
	- [x] 챌린지 컨트롤러 서비스간 리팩토링 진행
