### ISSUE TITLE
챌린지 디테일 페이지 프론트 구현

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#47]
## TODO
- [x] 챌린지 디테일 페이지 프론트 디자인 작업
	- [x] 참여 전 디테일 페이지
	- [x] 참여 후 디테일 페이지

--- 진행중

![image](https://github.com/Mirou-KnJ/Mirou_Main/assets/39723465/12f519b4-1063-4edc-b467-52538815ea3b)

![image](https://github.com/Mirou-KnJ/Mirou_Main/assets/39723465/373a3664-2d92-4fa9-b972-379c8df7978b)

![image](https://github.com/Mirou-KnJ/Mirou_Main/assets/39723465/9a7b95bb-bd16-49ea-8543-68bb377d6f59)
