### ISSUE TITLE
챌린지 참여 신청시 PrivateReward 생성, 회원마다 Detail에서 보여지는 보상이 다르도록

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#61]
## TODO
- [x] 챌린지 참여 신청시 PublicReward기반의 PrivateReward 생성.
- [x] detail 페이지에서 회원마다 보여지는 보상 내용이 다름
	- [x] 이미 참여한 회원 - PrivateReward 기반
	- [x] 아직 참여하지 않은 회원 -  PublicReward 기반
