### ISSUE TITLE
챌린지 디테일 페이지 프론트 작업

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#71]
## TODO
- [x] 참여 인원 표기
- [x] 참가 기한 포맷팅
- [x] 참가중일 경우 진행현황, 챌린지 피드 표기
- [x] 피드 출력 수정
