### ISSUE TITLE
챌린지, 생활지원금 관련 스케줄링 작업

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#84]
## TODO
- [x] 매일 정각에 종료 기한이 오늘 까지인 챌린지의 상태가 종료로 변경되어야 함
- [x] 매일 정각에 참여 기한이 오늘 까지인 챌린지 멤버의 상태가 종료로 변경되어야 함
- [x] 매주 월요일 정각에 모든 회원의 생활지원금이 3000포인트로 갱신되어야 함
