### ISSUE TITLE
Rq, Util 클래스 도입과 toastr알림 메세지 띄우기

### ISSUE THREAD

**Issue by SeoMoonk** [Mirou-KnJ/Mirou_Main#90]
## TODO
- [x] Rq 클래스 도입
- [x] Util 클래스 도입
- [x] toastr을 활용한 간이 알림 메시지 기능 (실제 알림 저장 x)
